### ISSUE TITLE
Desarrollo de ImageCell para cargar el modelo YOLO y hacer inferencias sobre imágenes

### ISSUE THREAD

**Issue by EstherRobotics** [EstherRobotics/AIVA_2023-Proyecto-Celulas#16]
Con el desarrollo de la clase ImageCell se pretende configurar el código necesario para cargar el modelo YOLO ya entrenado y la imagen correspondiente para poder realizar la detección y conteo de las células. 

Tiempo estimado: 4 días.

**Comment by vgomezm** [comment]
Tiempo empleado: 4 días.
