### ISSUE TITLE
Programación del algoritmo de detección y conteo de células

### ISSUE THREAD

**Issue by EstherRobotics** [EstherRobotics/AIVA_2023-Proyecto-Celulas#6]
Desarrollo de un algoritmo para la detección y conteo de células a partir de la base de datos y las anotaciones proporcionadas de las imágenes mediante técnicas de aprendizaje automático. 

Tiempo estimado: 7 días.

**Comment by vgomezm** [comment]
Tiempo empleado: 10 días.
