### ISSUE TITLE
Realización de pruebas con test unitarios del correcto funcionamiento del sistema

### ISSUE THREAD

**Issue by EstherRobotics** [EstherRobotics/AIVA_2023-Proyecto-Celulas#9]
Testeo del sistema mediante la ejecución de los test unitarios desarrollados sobre la aplicación con el objetivo de entrever posibles fallos y mejorar las funcionalidades ofrecidas. 

Tiempo estimado: 6 días.

**Comment by vgomezm** [comment]
Tiempo estimado: 6 días.
